AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  bill-api

  Billy API for expenses.

Globals:
  Function:
    Timeout: 30
Parameters:
  Env:
    Type: String
    Description: Environment.

Resources:
  BillyDataDLQ:
    Type: AWS::SQS::Queue

  BillyDataSQS:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 1800
      RedrivePolicy:
        deadLetterTargetArn: !Sub "${BillyDataDLQ.Arn}"
        maxReceiveCount: 5

  BillyDataFunction:
    Type: AWS::Serverless::Function
    Metadata:
      DockerTag: !Sub "${Env}.v1"
      DockerContext: ./app
      Dockerfile: Dockerfile
    Properties:
      PackageType: Image
      MemorySize: 1024
      Timeout: 300
      Environment:
        Variables:
          data_bucket: !Sub "{{resolve:ssm:/${Env}/data_bucket}}"
          ddb_table: !Sub "{{resolve:ssm:/${Env}/data_table}}"
          sns_topic: !Sub "{{resolve:ssm:/${Env}/sns_topic_arn}}"
      Architectures:
        - x86_64
      Policies:
        - Statement:
            - Action:
                - SNS:*
              Effect: Allow
              Resource: !Sub "{{resolve:ssm:/${Env}/sns_topic_arn}}"
            - Action:
                - s3:Get*
                - s3:List*
                - s3:Put*
              Effect: Allow
              Resource:
                - !Sub 'arn:aws:s3:::{{resolve:ssm:/${Env}/data_bucket}}'
                - !Sub 'arn:aws:s3:::{{resolve:ssm:/${Env}/data_bucket}}/*'
            - Action:
                - dynamodb:Get*
                - dynamodb:Query*
                - dynamodb:PutItem*
                - dynamodb:Delete*
                - dynamodb:Update*
                - dynamodb:DescribeStream*
                - dynamodb:DescribeTable*
                - dynamodb:Scan*
                - dynamodb:BatchWrite*
                - dynamodb:BatchRead*
              Effect: Allow
              Resource: !Sub 'arn:aws:dynamodb:*:*:table/{{resolve:ssm:/${Env}/data_table}}'
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !Sub "{{resolve:ssm:/${Env}/ddb_stream_arn}}"
            BatchSize: 100
            StartingPosition: LATEST
        DataDomainEvent:
          Type: SNS
          Properties:
            Topic: !Sub "{{resolve:ssm:/${Env}/sns_topic_arn}}"
            SqsSubscription:
              QueuePolicyLogicalId: BillyDataSQSPolicy
              QueueArn:
                Fn::GetAtt: BillyDataSQS.Arn
              QueueUrl:
                Ref: BillyDataSQS
              BatchSize: 1
            FilterPolicy:
              event_name:
                - job.created

