AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  bill-api

  Billy API for expenses.

Globals:
  Function:
    Timeout: 30
Parameters:
  Env:
    Type: String
    Description: Environment.

Resources:
  BillyDataFunction:
    Type: AWS::Serverless::Function
    Metadata:
      DockerTag: billy.data-v1
      DockerContext: ./app
      Dockerfile: Dockerfile
    Properties:
      PackageType: Image
      Environment:
        Variables:
          data_bucket: !Sub "{{resolve:ssm:/${Env}/data_bucket}}"
          ddb_table: !Sub "{{resolve:ssm:/${Env}/ddb_table}}"
      MemorySize: 1024
      Architectures:
        - x86_64
      Policies:
        - Statement:
            - Action:
                - s3:Get*
                - s3:List*
                - s3:Put*
              Effect: Allow
              Resource: !Sub 'arn:aws:s3:::{{resolve:ssm:/${Env}/data_bucket}}/*'
            - Action:
                - dynamodb:Get*
                - dynamodb:Query*
                - dynamodb:PutItem*
                - dynamodb:Delete*
                - dynamodb:Update*
                - dynamodb:DescribeStream*
                - dynamodb:DescribeTable*
                - dynamodb:Scan*
                - dynamodb:BatchWrite*
                - dynamodb:BatchRead*
              Effect: Allow
              Resource: !Sub 'arn:aws:dynamodb:*:*:table/{{resolve:ssm:/${Env}/ddb_table}}'
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !Sub "{{resolve:ssm:/${Env}/ddb_stream_arn}}"
            BatchSize: 100
            StartingPosition: LATEST