version = 0.1
[default]
[default.deploy]
[dev.deploy.parameters]
stack_name = "billy-dev"
s3_bucket = "aws-sam-cli-managed-billy-adolha"
s3_prefix = "iac/dev"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
parameter_overrides = [
    "Env=\"dev\"",
    "App=\"billy\"",
    "ApiUrl=\"https://vjmeqvvnq9.execute-api.eu-central-1.amazonaws.com/Dev\"",
    "DDBTableName=\"billy-data-table-dev\"",
    "CognitoUserPoolName=\"billy-user-pool-dev\"",
    "CognitoUserPoolClientName=\"billy-user-pool-client-dev\"",
    "AcmCertificateArn=\"arn:aws:acm:us-east-1:103050589342:certificate/628e5824-48a6-4f66-8d62-e9651b16b3bb\"",
    "RootDomainName=\"adolha.com\"",
    "UIDomainName=\"www.dev.billy\"",
    "UIBucketName=\"www.dev.billy.adolha.com\""
    ]
image_repositories = []

[prod.deploy.parameters]
stack_name = "billy-prod"
s3_bucket = "aws-sam-cli-managed-billy-adolha"
s3_prefix = "iac/prod"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
parameter_overrides = [
    "Env=\"prod\"",
    "App=\"billy\"",
    "ApiUrl=\"https://yq751grmbg.execute-api.eu-central-1.amazonaws.com/Dev\"",
    "DDBTableName=\"billy-data-table-prod\"",
    "CognitoUserPoolName=\"billy-user-pool-prod\"",
    "CognitoUserPoolClientName=\"billy-user-pool-client-prod\"",
    "AcmCertificateArn=\"arn:aws:acm:us-east-1:103050589342:certificate/628e5824-48a6-4f66-8d62-e9651b16b3bb\"",
    "RootDomainName=\"adolha.com\"",
    "UIDomainName=\"www.billy\"",
    "UIBucketName=\"www.billy.adolha.com\""
    ]
image_repositories = []
