version = 0.1
[default]
[default.deploy]
[dev.deploy.parameters]
stack_name = "billy-dev"
s3_bucket = "aws-sam-cli-managed-billy-adolha"
s3_prefix = "iac/dev"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = [
    "Env=\"dev\"",
    "DDBTableName=\"billy-data-dev\"",
    "CognitoUserPoolName=\"billy-user-pool-dev\"",
    "CognitoUserPoolClientName=\"billy-user-pool-client-dev\"",
    "RootDomainName=\"adolha.com\"",
    "UIDomainName=\"www.dev.billy\"",
    "UIBucketName=\"www.dev.billy.adolha.com\""
    ]
image_repositories = []

[prod.deploy.parameters]
stack_name = "billy-prod"
s3_bucket = "aws-sam-cli-managed-billy-adolha"
s3_prefix = "iac/prod"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = [
    "Env=\"prod\"",
    "DDBTableName=\"billy-data-prod\"",
    "CognitoUserPoolName=\"billy-user-pool-prod\"",
    "CognitoUserPoolClientName=\"billy-user-pool-client-prod\"",
    "RootDomainName=\"adolha.com\"",
    "UIDomainName=\"www.billy\"",
    "UIBucketName=\"www.billy.adolha.com\""
    ]
image_repositories = []
