version: 0.2
phases:
  build:
    commands:
      - echo $CODEBUILD_SRC_DIR
      - ls $CODEBUILD_SRC_DIR
      - cd $PROJECT_PATH
      - sam build
      - sam deploy --config-env $ENV --no-confirm-changeset --no-fail-on-empty-changeset
      - cd $CODEBUILD_SRC_DIR/billy-api
      - sam build
      - sam deploy --config-env $ENV --no-confirm-changeset --no-fail-on-empty-changeset