version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
      nodejs: 14
  build:
    commands:
      - echo $CODEBUILD_SRC_DIR/billy-ui
      - ls $CODEBUILD_SRC_DIR
      - ls $CODEBUILD_SRC_DIR/billy-ui
      - cd billy-ui
      - npm install --prefer-offline --no-audit
      - npm run build
      - aws s3 sync build s3://www.dev.billy.adolha.com
      - cd $CODEBUILD_SRC_DIR/billy-iac
      - sam build
      - sam deploy --config-env $ENV --no-confirm-changeset --no-fail-on-empty-changeset
      - cd $CODEBUILD_SRC_DIR/billy-api
      - sam build
      - sam deploy --config-env $ENV --no-confirm-changeset --no-fail-on-empty-changeset
      - ls $CODEBUILD_SRC_DIR/billy-iac
      - ls $CODEBUILD_SRC_DIR/billy-api
cache:
  paths:
    - '/root/.cache/pip/**/*'
    - '/root/.cache/pip3/**/*'
    - '/root/.npm/**/*'
artifacts:
  files:
    - '**/*'
