version: 0.2
phases:
  install:
    commands:
      - apt-get install -y npm
  build:
    commands:
      - echo $CODEBUILD_SRC_DIR
      - ls $CODEBUILD_SRC_DIR
      - cd billy-ui
      - npm install
      - npm run build
      - aws s3 sync build s3://www.dev.billy.adolha.com
      - cd $PROJECT_PATH
      - sam build
      - sam deploy --config-env $ENV --no-confirm-changeset --no-fail-on-empty-changeset
      - cd $CODEBUILD_SRC_DIR/billy-api
      - sam build
      - sam deploy --config-env $ENV --no-confirm-changeset --no-fail-on-empty-changeset