version: 0.2
phases:
  install:
    commands:
    - echo $CODEBUILD_SRC_DIR
    - ls $CODEBUILD_SRC_DIR
    - cd billy-api
    - pip3 install -r requirements.txt
  build:
    commands:
      - echo $CODEBUILD_SRC_DIR
      - echo $(pwd)
      - ls
      - ls $CODEBUILD_SRC_DIR
      - cd $CODEBUILD_SRC_DIR/billy-api/app
      - ls
      - python -m pytest ../tests/