version: 0.2
phases:
  install:
    commands:
    - echo $CODEBUILD_SRC_DIR
    - ls $CODEBUILD_SRC_DIR
    - cd billy-api
    - pip3 install -r requirements.txt
  build:
    commands:
      - echo $CODEBUILD_SRC_DIR
      - ls $CODEBUILD_SRC_DIR
      - cd billy-api
      - pytest -s -vvv tests/