version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
      nodejs: 14
  build:
    commands:
      - echo $CODEBUILD_SRC_DIR/billy-ui
      - ls $CODEBUILD_SRC_DIR
      - ls $CODEBUILD_SRC_DIR/billy-ui
      - cd billy-ui
      - ls node_modules
      - npm install --prefer-offline --no-audit
      - npm run build
      - aws s3 sync build s3://www.dev.billy.adolha.com
      - aws cloudfront create-invalidation --distribution-id $cloudfront_distribution_id --paths  '/*'
      - cd $CODEBUILD_SRC_DIR/billy-iac
      - sam build
      - sam deploy --config-env $ENV --no-confirm-changeset --no-fail-on-empty-changeset
      - cd $CODEBUILD_SRC_DIR/billy-data
      - sam build
      - sam deploy --config-env $ENV --no-confirm-changeset --no-fail-on-empty-changeset --resolve-image-repos
      - cd $CODEBUILD_SRC_DIR/billy-api
      - sam build
      - sam deploy --config-env $ENV --no-confirm-changeset --no-fail-on-empty-changeset
      - ls $CODEBUILD_SRC_DIR/billy-iac
cache:
  paths:
    - billy-ui/node_modules
artifacts:
  files:
    - '**/*'
