version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
      nodejs: 14
  build:
    commands:
      - echo $CODEBUILD_SRC_DIR
      - ls $CODEBUILD_SRC_DIR/billy-ui
      - ls billy-api
      - cd billy-ui
      - aws s3 sync build s3://www.billy.adolha.com
      - aws cloudfront create-invalidation --distribution-id $cloudfront_distribution_id --paths  '/*'
      - cd $CODEBUILD_SRC_DIR/billy-iac
      - sam deploy --config-env $ENV --no-confirm-changeset --no-fail-on-empty-changeset
      - cd $CODEBUILD_SRC_DIR/billy-data
      - sam deploy --config-env $ENV --no-confirm-changeset --no-fail-on-empty-changeset --image-repository "103050589342.dkr.ecr.eu-central-1.amazonaws.com/billy-data"
      - cd $CODEBUILD_SRC_DIR/billy-api
      - sam deploy --config-env $ENV --no-confirm-changeset --no-fail-on-empty-changeset

   
