version: 0.2
phases:
  build:
    install:
      commands:
      - echo $CODEBUILD_SRC_DIR
      - ls $CODEBUILD_SRC_DIR
      - cd billy-api
      - pip3 intall -r requirements.txt
    commands:
      - echo $CODEBUILD_SRC_DIR
      - ls $CODEBUILD_SRC_DIR
      - cd billy-api
      - pytest -s -vvv tests/