version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
    - echo $CODEBUILD_SRC_DIR
    - ls $CODEBUILD_SRC_DIR
    - echo "Running tests..."
    - cd billy-api
    - pip3 install -r requirements.txt
  build:
    commands:
      - echo $CODEBUILD_SRC_DIR
      - echo $(pwd)
      - ls
      - ls $CODEBUILD_SRC_DIR
      - cd $CODEBUILD_SRC_DIR/$PROJECT_PATH/app
      - ls
      - python -m pytest $TESTS_PATH