version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
      nodejs: 14
    commands:
      - pip3 install aws-sam-cli
  build:
    commands:
      - echo $CODEBUILD_SRC_DIR
      - ls $CODEBUILD_SRC_DIR
      - cd billy-ui
      - npm install
      - npm run build
      - aws s3 sync build s3://www.dev.billy.adolha.com
      - cd $CODEBUILD_SRC_DIR/billy-iac
      - sam build
      - sam deploy --config-env $ENV --no-confirm-changeset --no-fail-on-empty-changeset
      - cd $CODEBUILD_SRC_DIR/billy-api
      - sam build
      - sam deploy --config-env $ENV --no-confirm-changeset --no-fail-on-empty-changeset
cache:
  paths:
    - '/root/.pip/**/*'
    - '/root/.pip3/**/*'
    - '/root/.npm/**/*'
   
