version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "billy-cicd"
s3_bucket = "aws-sam-cli-managed-billy-adolha"
s3_prefix = "cicd"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = [
    ]
image_repositories = []
